# Generated by Django 4.2.1 on 2023-05-16 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveSmallIntegerField()),
                ('minor', models.PositiveSmallIntegerField()),
                ('patch', models.PositiveSmallIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.version')),
            ],
        ),
        migrations.CreateModel(
            name='RequestToReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.version')),
            ],
        ),
    ]
